import { useEffect, useRef, useState } from 'react';

/**
 * StructureViewer — a scrubber through a real training trajectory.
 *
 * On mount, loads `trajectory.json` and every checkpoint PDB from
 * `/af2-demo/alphafold2/`. Renders the ground truth (gray cartoon) overlaid
 * with the currently-selected training checkpoint (accent cartoon) using
 * 3Dmol.js. A slider lets the reader scrub from step 0 (random-init) through
 * to step 600 (converged). A metric panel shows the current loss and RMSDs.
 *
 * The demo data was generated by `scripts/build_af2_demo.py` — a 46-residue
 * overfit of 1CRN (crambin) on the tiny 0.09M-param profile, 600 steps, ~30s
 * on CPU. The sequence the model is folding is the same for every checkpoint;
 * only the weights change. Watching Cα RMSD drop from ~9.7 Å to ~2.3 Å as
 * you drag the slider is the "does this thing actually learn geometry?"
 * demonstration.
 */

type Checkpoint = {
  step: number;
  pdb: string;
  loss: number | null;
  backbone_rmsd_after_alignment: number;
  ca_rmsd_after_alignment: number;
  all_atom_rmsd_after_alignment: number;
  peptide_bond_mean: number;
  peptide_bond_max: number;
  peptide_bond_min: number;
};

type Trajectory = {
  pdb_id: string;
  sequence: string;
  num_residues: number;
  total_steps: number;
  model_profile: string;
  n_params_millions: number;
  ground_truth_pdb: string;
  checkpoints: Checkpoint[];
  loss_log: Array<{ step: number; loss: number }>;
};

const DATA_ROOT = '/af2-demo/alphafold2';

export default function StructureViewer() {
  const containerRef = useRef<HTMLDivElement | null>(null);
  const viewerRef = useRef<any>(null);
  const pdbCacheRef = useRef<Map<string, string>>(new Map());

  const [trajectory, setTrajectory] = useState<Trajectory | null>(null);
  const [idx, setIdx] = useState(0);
  const [playing, setPlaying] = useState(false);
  const [showGroundTruth, setShowGroundTruth] = useState(true);
  const [colorBy, setColorBy] = useState<'spectrum' | 'chain'>('spectrum');
  const [error, setError] = useState<string | null>(null);
  const [viewerReady, setViewerReady] = useState(false);

  // Load trajectory.json and all PDB files on mount.
  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const tjRes = await fetch(`${DATA_ROOT}/trajectory.json`);
        if (!tjRes.ok) throw new Error(`trajectory.json ${tjRes.status}`);
        const tj = (await tjRes.json()) as Trajectory;
        if (cancelled) return;

        const filesToFetch = [tj.ground_truth_pdb, ...tj.checkpoints.map((c) => c.pdb)];
        await Promise.all(
          filesToFetch.map(async (f) => {
            if (pdbCacheRef.current.has(f)) return;
            const r = await fetch(`${DATA_ROOT}/${f}`);
            if (!r.ok) throw new Error(`${f} ${r.status}`);
            const text = await r.text();
            pdbCacheRef.current.set(f, text);
          }),
        );
        if (cancelled) return;
        setTrajectory(tj);
      } catch (err) {
        if (!cancelled) setError((err as Error).message);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, []);

  // Initialize the 3Dmol viewer once the container is mounted.
  useEffect(() => {
    if (!containerRef.current || !trajectory || viewerRef.current) return;
    let cancelled = false;
    (async () => {
      try {
        const mod: any = await import('3dmol');
        if (cancelled || !containerRef.current) return;
        const $3Dmol = mod.default ?? mod;
        const bg = getComputedStyle(document.documentElement).getPropertyValue('--bg').trim() || '#14161a';
        const viewer = $3Dmol.createViewer(containerRef.current, {
          backgroundColor: bg,
          antialias: true,
        });
        viewerRef.current = viewer;
        setViewerReady(true);
      } catch (err) {
        if (!cancelled) setError(`Failed to load 3Dmol: ${(err as Error).message}`);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [trajectory]);

  // Render the current frame.
  useEffect(() => {
    const viewer = viewerRef.current;
    if (!viewer || !trajectory) return;
    const ckpt = trajectory.checkpoints[idx];
    if (!ckpt) return;

    viewer.removeAllModels();

    if (showGroundTruth) {
      const truthPdb = pdbCacheRef.current.get(trajectory.ground_truth_pdb);
      if (truthPdb) {
        viewer.addModel(truthPdb, 'pdb');
        viewer.setStyle({ model: 0 }, { cartoon: { color: '#8a8f95', opacity: 0.55 } });
      }
    }

    const predPdb = pdbCacheRef.current.get(ckpt.pdb);
    if (predPdb) {
      const modelIdx = showGroundTruth ? 1 : 0;
      viewer.addModel(predPdb, 'pdb');
      const style =
        colorBy === 'spectrum'
          ? { cartoon: { color: 'spectrum' } }
          : { cartoon: { color: '#e64b5c' } };
      viewer.setStyle({ model: modelIdx }, style);
    }

    // Only zoom on first render (when there's no prior model state), otherwise
    // keep the current camera orientation so scrubbing doesn't rubber-band.
    if (idx === 0 && !viewer.__annotatedDidZoom) {
      viewer.zoomTo();
      viewer.__annotatedDidZoom = true;
    }
    viewer.render();
  }, [trajectory, idx, showGroundTruth, colorBy, viewerReady]);

  // Auto-play through the checkpoints.
  useEffect(() => {
    if (!playing || !trajectory) return;
    const id = window.setInterval(() => {
      setIdx((i) => {
        const next = i + 1;
        if (next >= trajectory.checkpoints.length) {
          setPlaying(false);
          return i;
        }
        return next;
      });
    }, 650);
    return () => window.clearInterval(id);
  }, [playing, trajectory]);

  if (error) {
    return (
      <figure className="sv-root">
        <div className="sv-error">
          Could not load trajectory: <code>{error}</code>. The demo data lives under
          <code>public/af2-demo/alphafold2/</code> — regenerate it with
          <code>python scripts/build_af2_demo.py</code>.
        </div>
      </figure>
    );
  }

  if (!trajectory) {
    return (
      <figure className="sv-root">
        <div className="sv-loading">Loading training trajectory…</div>
      </figure>
    );
  }

  const ckpt = trajectory.checkpoints[idx];
  const lossDisplay = ckpt.loss === null ? '—' : ckpt.loss.toFixed(3);

  // Build a small SVG loss curve (not full-chart, just a sparkline with a marker for
  // the current step). The full loss_log has many more points than the checkpoints.
  const losses = trajectory.loss_log;
  const losssvgW = 280;
  const losssvgH = 70;
  const maxLoss = Math.max(...losses.map((l) => l.loss));
  const minLoss = Math.min(...losses.map((l) => l.loss));
  const lossRange = Math.max(0.001, maxLoss - minLoss);
  const lossPoints = losses
    .map((l, i) => {
      const x = (i / (losses.length - 1)) * losssvgW;
      const y = losssvgH - ((l.loss - minLoss) / lossRange) * (losssvgH - 8) - 4;
      return `${x.toFixed(1)},${y.toFixed(1)}`;
    })
    .join(' ');
  const currentStep = ckpt.step;
  const markerIdx = losses.findIndex((l) => l.step >= currentStep);
  const markerX = (Math.max(0, markerIdx) / Math.max(1, losses.length - 1)) * losssvgW;

  return (
    <figure className="sv-root">
      <div className="sv-layout">
        <div className="sv-canvas-shell">
          <div ref={containerRef} className="sv-canvas" />
          <div className="sv-legend">
            <span><span className="sv-sw sv-sw--truth" /> ground truth</span>
            <span><span className="sv-sw sv-sw--pred" /> prediction @ step {ckpt.step}</span>
          </div>
        </div>

        <div className="sv-panel">
          <div className="sv-header">
            <span className="sv-pdb-id">PDB {trajectory.pdb_id.toUpperCase()}</span>
            <span className="sv-model">({trajectory.model_profile} · {trajectory.n_params_millions}M params)</span>
          </div>

          <div className="sv-seq" aria-label="Protein sequence">
            {trajectory.sequence}
          </div>

          <div className="sv-metrics">
            <div className="sv-metric">
              <span className="sv-metric-k">step</span>
              <span className="sv-metric-v">{ckpt.step} / {trajectory.total_steps}</span>
            </div>
            <div className="sv-metric">
              <span className="sv-metric-k">loss</span>
              <span className="sv-metric-v">{lossDisplay}</span>
            </div>
            <div className="sv-metric">
              <span className="sv-metric-k">Cα RMSD</span>
              <span className="sv-metric-v">{ckpt.ca_rmsd_after_alignment.toFixed(2)} Å</span>
            </div>
            <div className="sv-metric">
              <span className="sv-metric-k">backbone RMSD</span>
              <span className="sv-metric-v">{ckpt.backbone_rmsd_after_alignment.toFixed(2)} Å</span>
            </div>
            <div className="sv-metric">
              <span className="sv-metric-k">all-atom RMSD</span>
              <span className="sv-metric-v">{ckpt.all_atom_rmsd_after_alignment.toFixed(2)} Å</span>
            </div>
          </div>

          <div className="sv-loss-sparkline" aria-label="Loss over training steps">
            <div className="sv-sparkline-label">training loss</div>
            <svg viewBox={`0 0 ${losssvgW} ${losssvgH}`} preserveAspectRatio="none" className="sv-spark-svg">
              <polyline points={lossPoints} className="sv-spark-path" />
              <line x1={markerX} y1={0} x2={markerX} y2={losssvgH} className="sv-spark-marker" />
            </svg>
          </div>

          <div className="sv-controls">
            <input
              type="range"
              min={0}
              max={trajectory.checkpoints.length - 1}
              step={1}
              value={idx}
              onChange={(e) => {
                setPlaying(false);
                setIdx(Number(e.currentTarget.value));
              }}
              aria-label="Training checkpoint scrubber"
            />
            <button className="sv-btn" onClick={() => setPlaying((p) => !p)} type="button">
              {playing ? 'Pause' : 'Play'}
            </button>
            <button
              className="sv-btn"
              onClick={() => {
                setPlaying(false);
                setIdx(0);
              }}
              type="button"
            >
              Reset
            </button>
          </div>

          <div className="sv-toggles">
            <label className="sv-toggle">
              <input
                type="checkbox"
                checked={showGroundTruth}
                onChange={(e) => setShowGroundTruth(e.currentTarget.checked)}
              />
              <span>Overlay ground truth</span>
            </label>
            <label className="sv-toggle">
              <span>Color:</span>
              <select
                value={colorBy}
                onChange={(e) => setColorBy(e.currentTarget.value as 'spectrum' | 'chain')}
              >
                <option value="spectrum">Spectrum (N → C)</option>
                <option value="chain">Solid accent</option>
              </select>
            </label>
          </div>
        </div>
      </div>

      <style>{`
        .sv-root {
          margin: 1.5rem 0;
          border: 1px solid var(--rule);
          border-radius: 6px;
          padding: 0.9rem 1rem 1rem;
          background: color-mix(in oklab, var(--bg) 94%, var(--rule) 6%);
          font-family: var(--font-sans);
        }
        .sv-layout {
          display: grid;
          grid-template-columns: 1fr;
          gap: 1rem;
        }
        @media (min-width: 820px) {
          .sv-layout { grid-template-columns: 1.4fr 1fr; }
        }
        .sv-canvas-shell {
          position: relative;
          height: 420px;
          border-radius: 4px;
          overflow: hidden;
          background: linear-gradient(180deg, color-mix(in oklab, var(--bg) 88%, var(--rule) 12%), var(--bg));
        }
        .sv-canvas {
          position: absolute;
          inset: 0;
          width: 100% !important;
          height: 100% !important;
        }
        .sv-legend {
          position: absolute;
          bottom: 0.6rem;
          left: 0.7rem;
          display: flex;
          gap: 1rem;
          font-size: 0.72rem;
          color: var(--fg-muted);
          pointer-events: none;
        }
        .sv-legend span { display: inline-flex; align-items: center; gap: 0.3rem; }
        .sv-sw { display: inline-block; width: 10px; height: 10px; border-radius: 2px; }
        .sv-sw--truth { background: #8a8f95; opacity: 0.6; }
        .sv-sw--pred { background: #e64b5c; }

        .sv-panel {
          display: flex;
          flex-direction: column;
          gap: 0.7rem;
          font-size: 0.88rem;
        }
        .sv-header {
          display: flex;
          align-items: baseline;
          gap: 0.4rem;
          font-weight: 600;
          font-size: 0.92rem;
        }
        .sv-model {
          color: var(--fg-muted);
          font-weight: 400;
          font-size: 0.8rem;
        }
        .sv-seq {
          font-family: var(--font-mono);
          font-size: 0.73rem;
          padding: 0.5rem 0.6rem;
          background: color-mix(in oklab, var(--rule) 30%, transparent);
          border-radius: 4px;
          word-break: break-all;
          line-height: 1.45;
          color: var(--fg);
        }

        .sv-metrics {
          display: grid;
          grid-template-columns: auto 1fr;
          gap: 0.15rem 0.8rem;
          font-family: var(--font-mono);
          font-size: 0.82rem;
        }
        .sv-metric { display: contents; }
        .sv-metric-k { color: var(--fg-muted); }
        .sv-metric-v { color: var(--fg); font-variant-numeric: tabular-nums; }

        .sv-loss-sparkline {
          display: flex;
          flex-direction: column;
          gap: 0.2rem;
        }
        .sv-sparkline-label {
          font-size: 0.7rem;
          letter-spacing: 0.08em;
          text-transform: uppercase;
          color: var(--fg-muted);
        }
        .sv-spark-svg {
          width: 100%;
          height: 62px;
          display: block;
          border: 1px solid var(--rule);
          border-radius: 3px;
          background: color-mix(in oklab, var(--bg) 90%, var(--rule) 10%);
        }
        .sv-spark-path {
          fill: none;
          stroke: var(--accent);
          stroke-width: 1.3;
          stroke-linejoin: round;
          opacity: 0.9;
        }
        .sv-spark-marker {
          stroke: var(--accent);
          stroke-width: 1;
          stroke-dasharray: 2 2;
          opacity: 0.65;
        }

        .sv-controls {
          display: flex;
          align-items: center;
          gap: 0.5rem;
        }
        .sv-controls input[type="range"] { flex: 1; }
        .sv-btn {
          font-size: 0.78rem;
          padding: 0.3rem 0.7rem;
          border: 1px solid var(--rule);
          border-radius: 3px;
          background: transparent;
          color: var(--fg);
          cursor: pointer;
        }
        .sv-btn:hover { border-color: var(--fg-muted); }

        .sv-toggles {
          display: flex;
          flex-wrap: wrap;
          gap: 0.75rem;
          font-size: 0.82rem;
          color: var(--fg-muted);
        }
        .sv-toggle {
          display: inline-flex;
          align-items: center;
          gap: 0.4rem;
        }
        .sv-toggle select {
          border: 1px solid var(--rule);
          border-radius: 3px;
          background: transparent;
          color: var(--fg);
          padding: 0.15rem 0.3rem;
          font: inherit;
        }

        .sv-error, .sv-loading {
          padding: 2rem 1rem;
          text-align: center;
          color: var(--fg-muted);
          font-size: 0.88rem;
        }
        .sv-error code {
          display: inline;
          padding: 0.05em 0.3em;
          border: 1px solid var(--rule);
          border-radius: 3px;
          margin: 0 0.2em;
          font-size: 0.82em;
        }
      `}</style>
    </figure>
  );
}
